// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txeveoapiwaqkrvwwcqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4ZXZlb2FwaXdhcWtydnd3Y3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDU3MTgsImV4cCI6MjA3MDY4MTcxOH0.qgTJxsfsW9zo2bSQvoZPQMpMn7ID1cWj15FDH3HLQ2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});